[package]
name = "gerber_viewer"
version = "0.4.0"
documentation = "https://docs.rs/gerber-viewer/"
repository = "https://github.com/MakerPnP/gerber-viewer"
homepage = "https://github.com/MakerPnP/gerber-viewer"
license = "MIT OR Apache-2.0"
authors = [
    "Dominic Clifton <me@dominicclifton.name>",
]
description = "A cargo crate for rendering Gerber files."
readme = "README.md"
keywords = ["gerber", "rs274x", "render", "gui", "egui"]
include = [
    "**/*.rs",
    "Cargo.toml",
    "README.md",
    "LICENSE-*",
]
edition = "2021"

[dependencies]
# Rendering (optional, see README.md)
egui = { version = "0.32.0", optional = true }

# Gerber files
gerber-types = "0.6.0"
# currently un-released, using latest gerber_types with updates to support macro expressions
#gerber-types = { git = "https://github.com/MakerPnP/gerber-types.git", rev = "bc303fa1d946933301d3459bef42a0c984683301"}
#gerber-types = { path = "../gerber-types" }

# Gerber parser (optional, see README.md)
gerber_parser = { version = "0.3.0", optional = true }
#gerber_parser = { git = "https://github.com/makerpnp/gerber-parser.git", rev = "fcad868d9e1423d49a5acdb9bfc37016b034f445", optional = true }
#gerber_parser = { path = "../gerber-parser", optional = true }

# Math
rand = "0.9.1"
lyon = "1.0"
nalgebra = { version = "0.33.2" , default-features = false }

# Errors
thiserror = "2.0.12"

# Logging
log = "0.4"

# Profiling
profiling = { version = "1.0.16" }

# Serialization
serde = { version = "1.0.219", optional = true, features = ["derive"] }

[features]
default = ["types", "parser", "egui"]

# add egui rendering API
egui = ["dep:egui"]

# just adds a re-export of gerber-parser.
parser = ["dep:gerber_parser"]
# just adds a re-export of gerber-types, the gerber-types will still be used.
types = []

serde = ["dep:serde"]

# include test helpers
testing = []

# enable to create profiling scopes for each type of gerber primitive
profile-renderables = []

[dev-dependencies]
rstest = "0.25.0"
env_logger = "0.11.8"
gerber_viewer = { path = ".", features = ["testing"] }
criterion = "0.5"
rand = "0.9.1"

[[bench]]
name = "transform_benchmark"
harness = false

