[package]
name = "gerber_viewer_demo"
version = "0.1.0"
edition = "2024"
authors = ["Dominic Clifton <me@dominicclifton.name>"]

[dependencies]
egui = "0.31.1"
eframe = "0.31.1"
gerber_viewer = { path = "..", features = ["egui", "parser", "types"] }
env_logger = "0.11.8"
profiling = "1.0.16"
puffin_http = { version = "0.16.1", optional = true}
tracing = "0.1.41"

[features]
profile-with-puffin = [
    "profiling/profile-with-puffin",
    "dep:puffin_http",
]

# delete this, it's just a cargo workspace workaround
[workspace]